apiVersion: v1
kind: Service
metadata:
  name: test-ip-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: test-ip
    app.kubernetes.io/name: test-ip
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31111
      protocol: TCP
